// Author                 : Seityagiya Terlekchi
// Contacts               : terlekchiseityaya@gmail.com
// Creation Date          : 2020.05
// License Link           : https://spdx.org/licenses/LGPL-2.1-or-later.html
// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright © 2020-2025 Seityagiya Terlekchi. All rights reserved.

#include "test.h"
#include "yaya_endian.h"

int test_endian(void) {
#if IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER)
    ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER)
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER)
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER)
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
    ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif
    return 0;
}
