// Author                 : Seityagiya Terlekchi
// Contacts               : seityaya@ukr.net
// License Link           : https://spdx.org/licenses/LGPL-2.1-or-later.html
// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright © Seityagiya Terlekchi. All rights reserved.

#include "yaya_unit.h"

#include "yaya_endian.h"

UT_FUNC_GEN(test_endian) {
    UT_GROUP_BEG(endian) {

#if IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER)
        UT_ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER)
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER)
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif

#if IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER)
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(BIG_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_FL(IS_CURRENT_BYTE_ORDER(MID_LIT_ENDIAN_BYTE_ORDER));
        UT_ASSERT_BOOL_TR(IS_CURRENT_BYTE_ORDER(MID_BIG_ENDIAN_BYTE_ORDER));
#endif
    } UT_GROUP_END;
}
